name: Build and test Minestom

on:
  pull_request:

jobs:
  # Thanks paper: https://github.com/papermc/paper/blob/master/.github/workflows/close_invalid_prs.yml
  validate:
    if: |
      github.repository != github.event.pull_request.head.repo.full_name &&
      (
        github.head_ref == 'master' ||
        github.event.pull_request.head.repo.owner.type != 'User'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        id: "master_branch"
        if: github.head_ref == 'master'
        with:
          comment: "Please do not open pull requests from the `master` branch, create a new branch instead."

      - uses: superbrothers/close-pull-request@v3
        id: "org_account"
        if: github.event.pull_request.head.repo.owner.type != 'User' && steps.master_branch.outcome == 'skipped'
        with:
          comment: "Please do not open pull requests from non-user accounts like organisations. Create a fork on a user account instead."
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup gradle cache
      uses: burrunan/gradle-cache-action@v1
      with:
        save-generated-gradle-jars: false
        save-local-build-cache: false
        save-gradle-dependencies-cache: true
        save-maven-dependencies-cache: true
        # Ignore some of the paths when caching Maven Local repository
        maven-local-ignore-paths: |
          net/minestom/
    - name: Build Minestom
      run: ./gradlew classes testClasses
    - name: Run Minestom tests
      run: ./gradlew test
